// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type AuthCode struct {
	Code          string         `json:"code"`
	ClientID      string         `json:"client_id"`
	RedirectUri   string         `json:"redirect_uri"`
	Sub           string         `json:"sub"`
	Scope         sql.NullString `json:"scope"`
	CodeChallenge sql.NullString `json:"code_challenge"`
	Nonce         sql.NullString `json:"nonce"`
	CreatedAt     time.Time      `json:"created_at"`
	ExpiresAt     time.Time      `json:"expires_at"`
}

type User struct {
	ID             int64          `json:"id"`
	Name           string         `json:"name"`
	HashedPassword string         `json:"hashed_password"`
	Email          string         `json:"email"`
	EmailVerified  bool           `json:"email_verified"`
	Gender         sql.NullString `json:"gender"`
	CreatedAt      time.Time      `json:"created_at"`
}
