// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type AuthCode struct {
	Code          string         `json:"code"`
	ClientID      string         `json:"client_id"`
	RedirectUri   string         `json:"redirect_uri"`
	Sub           string         `json:"sub"`
	Scope         sql.NullString `json:"scope"`
	CodeChallenge sql.NullString `json:"code_challenge"`
	Nonce         sql.NullString `json:"nonce"`
	CreatedAt     time.Time      `json:"created_at"`
	ExpiresAt     time.Time      `json:"expires_at"`
}

type Client struct {
	ID           string    `json:"id"`
	ClientName   string    `json:"client_name"`
	ClientSecret string    `json:"client_secret"`
	RedirectUris []string  `json:"redirect_uris"`
	CreatedAt    time.Time `json:"created_at"`
}

type Permission struct {
	ID        int32        `json:"id"`
	UserID    int32        `json:"user_id"`
	ClientID  string       `json:"client_id"`
	Allowed   bool         `json:"allowed"`
	GrantedAt sql.NullTime `json:"granted_at"`
}

type User struct {
	ID             int64          `json:"id"`
	Name           string         `json:"name"`
	HashedPassword string         `json:"hashed_password"`
	Email          string         `json:"email"`
	EmailVerified  bool           `json:"email_verified"`
	Gender         sql.NullString `json:"gender"`
	CreatedAt      time.Time      `json:"created_at"`
}
