// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateAuthCode(ctx context.Context, arg CreateAuthCodeParams) (AuthCode, error)
	GetAuthCode(ctx context.Context, code string) (AuthCode, error)
}

var _ Querier = (*Queries)(nil)
