// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, hashed_password, email, gender, email_verified)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, hashed_password, email, email_verified, gender, created_at, sub
`

type CreateUserParams struct {
	Name           string         `json:"name"`
	HashedPassword string         `json:"hashed_password"`
	Email          string         `json:"email"`
	Gender         sql.NullString `json:"gender"`
	EmailVerified  bool           `json:"email_verified"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Name,
		arg.HashedPassword,
		arg.Email,
		arg.Gender,
		arg.EmailVerified,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HashedPassword,
		&i.Email,
		&i.EmailVerified,
		&i.Gender,
		&i.CreatedAt,
		&i.Sub,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, hashed_password, email, email_verified, gender, created_at, sub FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HashedPassword,
		&i.Email,
		&i.EmailVerified,
		&i.Gender,
		&i.CreatedAt,
		&i.Sub,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, hashed_password, email, email_verified, gender, created_at, sub FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HashedPassword,
		&i.Email,
		&i.EmailVerified,
		&i.Gender,
		&i.CreatedAt,
		&i.Sub,
	)
	return i, err
}

const getUserBySub = `-- name: GetUserBySub :one
SELECT id, name, hashed_password, email, email_verified, gender, created_at, sub FROM users WHERE sub = $1
`

func (q *Queries) GetUserBySub(ctx context.Context, sub uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserBySub, sub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HashedPassword,
		&i.Email,
		&i.EmailVerified,
		&i.Gender,
		&i.CreatedAt,
		&i.Sub,
	)
	return i, err
}
